// support-ticket-system-fe/src/components/auth/PasswordToggle.jsx
import { EyeIcon, EyeOffIcon } from '../../assets/icons';

const PasswordToggle = ({ show, onToggle }) => (
  <button
    type="button"
    onClick={onToggle}
    className="absolute inset-y-0 right-0 pr-4 flex items-center text-gray-400 hover:text-gray-600"
  >
    {show ? <EyeIcon /> : <EyeOffIcon />}
  </button>
);

export default PasswordToggle;

// support-ticket-system-nuxt/app/components/auth/PasswordToggle.vue
<template>
  <button
    type="button"
    @click="$emit('toggle')"
    class="absolute inset-y-0 right-0 pr-4 flex items-center text-gray-400 hover:text-gray-600"
  >
    <EyeIcon v-if="show" />
    <EyeOffIcon v-else />
  </button>
</template>

<script setup>
defineProps({
  show: Boolean
})

defineEmits(['toggle'])
</script>
