// support-ticket-system-nuxt/app/components/form/FormInput.vue
<template>
    <div>
        <label class="block text-gray-700 text-sm font-medium mb-2">{{ label }}</label>
        <input :type="type" :name="name" :value="modelValue" @input="$emit('update:modelValue', $event.target.value)"
            :placeholder="placeholder" :required="required"
            :class="['w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none', className]" />
    </div>
</template>

<script setup>
defineProps({
    label: String,
    name: String,
    modelValue: [String, Number],
    type: {
        type: String,
        default: 'text'
    },
    required: {
        type: Boolean,
        default: false
    },
    placeholder: {
        type: String,
        default: ''
    },
    className: {
        type: String,
        default: ''
    }
})

defineEmits(['update:modelValue'])
</script>

// support-ticket-system-fe/src/components/form/FormInput.jsx
const FormInput = ({ label, name, value, onChange, type = 'text', required = false, placeholder = '', className = '' }) => {
  return (
    <div>
      <label className="block text-gray-700 text-sm font-medium mb-2">{label}</label>
      <input
        type={type}
        name={name}
        value={value}
        onChange={onChange}
        placeholder={placeholder}
        className={`w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none ${className}`}
        required={required}
      />
    </div>
  );
};

export default FormInput;
