// support-ticket-system-fe/src/pages/Profile.jsx
import { useAuth } from '../contexts/AuthContext';
import ProfileInfoCard from '../components/profile/ProfileInfoCard';
import PasswordChangeCard from '../components/profile/PasswordChangeCard';

const Profile = () => {
    const { user, logout } = useAuth();

    return (
        <div className="p-12 max-w-4xl">
            <h1 className="text-4xl font-bold text-gray-900 mb-8">Profile</h1>
            <ProfileInfoCard user={user} />
            <PasswordChangeCard logout={logout} />
        </div>
    );
};

export default Profile;

// support-ticket-system-nuxt/app/pages/profile.vue
<template>
  <div class="p-12 max-w-4xl">
    <h1 class="text-4xl font-bold text-gray-900 mb-8">Profile</h1>
    <ProfileInfoCard v-if="user" :user="user" />
    <PasswordChangeCard :logout="logout" />
  </div>
</template>

<script setup>
import ProfileInfoCard from '~/components/profile/ProfileInfoCard.vue'
import PasswordChangeCard from '~/components/profile/PasswordChangeCard.vue'

definePageMeta({
  middleware: 'auth',
  layout: 'default'
})

const { user, logout } = useAuth()
</script>
