// support-ticket-system-nuxt/app/components/users/UsersTable.vue
<template>
    <div class="bg-white rounded-lg shadow-sm overflow-hidden">
        <div v-if="users && users.length > 0" class="overflow-x-auto">
            <table class="min-w-full divide-y divide-gray-200">
                <UsersTableHeader />
                <tbody class="bg-white divide-y divide-gray-200">
                    <UsersTableRow v-for="user in users" :key="user.id" :user="user"
                        :reset-password-id="resetPasswordId" @click="$emit('userClick', user.id)"
                        @reset-password="(userId, userName) => $emit('resetPassword', userId, userName)" />
                </tbody>
            </table>
        </div>

        <div v-else class="text-center py-12">
            <p class="text-gray-500">No users found</p>
        </div>
    </div>
</template>

<script setup>
import UsersTableHeader from './UsersTableHeader.vue'
import UsersTableRow from './UsersTableRow.vue'

defineProps({
    users: {
        type: Array,
        default: () => []
    },
    resetPasswordId: Number
})

defineEmits(['userClick', 'resetPassword'])
</script>

// support-ticket-system-fe/src/components/users/UsersTable.jsx
import UsersTableHeader from './UsersTableHeader';
import UsersTableRow from './UsersTableRow';
import { useNavigate } from 'react-router-dom';

const UsersTable = ({ users, resetPasswordId, onResetPassword }) => {
    const navigate = useNavigate();
    return (
        <div className="bg-white rounded-lg shadow-sm overflow-hidden">
            <div className="overflow-x-auto">
                <table className="min-w-full divide-y divide-gray-200">
                    <UsersTableHeader />
                    <tbody className="bg-white divide-y divide-gray-200">
                        {users.map((user) => (
                            <UsersTableRow
                                key={user.id}
                                user={user}
                                resetPasswordId={resetPasswordId}
                                onResetPassword={onResetPassword}
                                onClick={() => navigate(`/users/${user.id}`)}
                            />
                        ))}
                    </tbody>
                </table>
            </div>

            {users.length === 0 && (
                <div className="text-center py-12">
                    <p className="text-gray-500">No users found</p>
                </div>
            )}
        </div>
    );
};

export default UsersTable;
